// Geen-Dolfijn/src/routes/+page.svelte
<script lang="ts">
  import { randomInt } from "$lib/main.ts";
  import sizzle from "../Images/NotBaldCat.jpg";
  import willy from "../Images/BaldCat.jpg";
  import okkie from "../Images/Okkie<3.jpg";

  const titles: string[] = [
    "Ik ben een titel",
    "I am a title",
    "Je suis une titre",
    "Ich bin ein Titel",
    "Jag är en title",
    "Minä olen titteli",
    "Es esmu tituls",
  ];
</script>

<div class="header">
  <h1>{titles[randomInt(0, titles.length - 1)]}</h1>
</div>

<div class="containerIntro">
  <div class="intro">
    <p>
      Who am I? That is a good question. I do not know exactly either, but I can
      tell you what I am not: I am Definitely Not A Dolphin.
    </p>

    <p>
      What am I doing here? I am a math nerd, not computer nerd. My friends
      indoctrinated me into coding and I do not know whether I like it or not.
    </p>

    <p>
      Since I am still mainly a math nerd, check out my page with my favorite
      math thingeys!
    </p>
  </div>

  <img alt="My cat!" src={sizzle} class="sizzle" />
</div>

<div class="containerIntro">
  <img alt="My other cat!" src={okkie} class="sizzle" />

  <div class="intro">
    <p class="nob">I "know" a few programming languages:</p>

    <ul class="not">
      <li>Python (never again)</li>
      <li>Javascript / TypeScript</li>
      <li>Svelte (yes I'm counting that, best framework btw)</li>
      <li>C++</li>
    </ul>

    <p>
      Also I am still learning so if you see code that just completely sucks: Do
      not worry, I am aware of it. Just leave an issue and I'll look into it. I
      am too busy skateboarding on the learning curve.
    </p>
  </div>
</div>

// routes/index.tsx
import HackatimeStats from "@/islands/HackatimeStats.tsx";
import LastFMStats from "@/islands/LastfmStats.tsx";
import { randomInt } from "@/lib/utils.ts";
import { define } from "@/utils.ts";
import { useDraggable } from "@neodrag/react";
import sizzle from "/NotBaldCat.jpg";
import okkie from "/Okkie<3.jpg";
import { useRef } from "preact/hooks";

export default define.page(function Home() {
  const draggableRef = useRef(null);
  useDraggable(draggableRef);
  const birthTimestamp = new Date("2008-12-31T13:00:00Z").getTime(); // Replace with your actual birth date
  const calculateAge = () =>
    ((Date.now() - birthTimestamp) / 31557600000).toFixed(8);

  const age = calculateAge();

  const titles: string[] = [
    "Ik ben een titel",
    "I am a title",
    "Je suis une titre",
    "Ich bin ein Titel",
    "Jag är en tittel",
    "Minä olen titteli",
    "Es esmu tituls",
  ] as const;

  return (
    <>
      <div class="header" ref={draggableRef}>
        <h1>{titles[randomInt(0, titles.length - 1)]}</h1>
      </div>

      <div class="containerStandard">
        <div class="standardBlock">
          <h1 style="color: var(--linkblue)" class="nob not">Hello there!</h1>

          <p class="not">
            My name is Derek Verduijn, aka Definitely Not A Dolphin or
            Killioiden Kaa. I am an {/* ToDo: make this update automatically */}
            {age}{" "}
            y/o computer and math enthusiast from The Netherlands studying
            Applied Mathematics @ TUDelft. Other interests include Finnish and
            chess.
          </p>

          <h3 class="nob not" style="color: var(--mathcolor);">Last.fm</h3>

          <LastFMStats />
        </div>

        <img alt="My cat!" src={sizzle} class="imageStandard" />
      </div>

      <div class="containerStandard">
        <img alt="My other cat!" src={okkie} class="imageStandard" />

        <div class="standardBlock">
          <h1 style="color: var(--linkblue)" class="nob not">Coding</h1>
          <p class="nob not">
            Currently I am working on Funktio and Geen-Dolfijn.
          </p>

          <p>
            To busy skateboarding on the learning curve to write code that
            doesn't suck.
          </p>

          <h3 style="color: var(--mathcolor)" class="nob not">Hackatime</h3>

          <HackatimeStats />
        </div>
      </div>
    </>
  );
});
